env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:svelte/recommended
  - plugin:@typescript-eslint/recommended
overrides:
  - files: ["*.svelte"]
    parser: "svelte-eslint-parser"
    parserOptions:
      parser: "@typescript-eslint/parser"
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - "@typescript-eslint"
rules:
  indent:
    - error
    - 4
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-control-regex:
    - off
  "@typescript-eslint/ban-ts-comment":
    - off
  svelte/no-at-html-tags:
    - off
