name: Page eslint

on:
  push:
    paths:
      - "**.ts"
      - "**.js"
      - "**.svelte"
      - ".eslintrc.yml"
      - ".stylelintrc.json"
      - ".github/workflows/eslint.yml"
  pull_request:
    branches: [master]
    paths:
      - "**.ts"
      - "**.js"
      - "**.svelte"
      - ".eslintrc.yml"
      - ".stylelintrc.json"
      - ".github/workflows/eslint.yml"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Yarn
        run: |
          yarn install
          yarn lint
