name: Github pages

on:
  push:
    branches: [main]
    paths:
      - ".github/workflows/page.yml"
      - "**.ts"
      - "**.js"
      - "**.md"
      - "**.svg"
      - "**.html"
      - "**.scss"
      - "**.svelte"
      - "wasm/**"
      - "package.json"
  pull_request:
    branches: [main]
    paths:
        - ".github/workflows/page.yml"
        - "**.ts"
        - "**.js"
        - "**.md"
        - "**.svg"
        - "**.html"
        - "**.scss"
        - "**.svelte"
        - "wasm/**"
        - "package.json"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"

# 保证权限合适
permissions:
  contents: read
  pages: write
  id-token: write

# 避免跳过部署
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build github pages
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      # WASM
      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v13
      - name: WASM build
        working-directory: "./wasm"
        run: |
          emmake make
      # 网页
      - name: Yarn
        run: |
          yarn install
          yarn build
      # 移除node module
      - name: Remove node module
        run: |
          rm -rf node_modules
      # 把文件移动到_site
      - name: Move outputs
        run: |
          mkdir _site
          mv dist/* _site
      # 打包
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  # 进行部署 (仅main branch)
  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
